### ISSUE TITLE
看不懂这个工具有什么用？

### ISSUE THREAD

**Issue by xiaohuazi123** [taojy123/sqlx#1]
看不懂这个工具有什么用？

sqlx生成的都是mysql自带的 函数语法，那这个sqlx具体有什么用，真的完全搞不懂

**Comment by taojy123** [comment]
先写 sqlx ，然后通过插件编译成 sql，在 mysql 上执行。
比较适用于要写的 sql 特别长的场景。
比如一个 sql 有几百行，如果传统写法，写完以后可能过两天就自己都看不明白了，不方便维护

**Comment by itswuanran** [comment]
基本的数仓引擎都会提供CTE功能，这个工具实在是鸡肋

**Comment by xiaohuazi123** [comment]
> 基本的数仓引擎都会提供CTE功能，这个工具实在是鸡肋

对的，鸡肋
